services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:5
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: go run /app/cmd/main.go

  db:
    image: postgres:latest
    restart: on-failure:5
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - 5432

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8000:80